### ISSUE TITLE
User Story 001: Expose SysML Models as an API

### ISSUE THREAD

**Issue by KBR-Autocorrect** [KBR-DREAMM-Team/Process-Documentation-Demo#1]
## Top Level
As a Systems Engineer, I want to expose the data I am authoring in my SysML Model to others so that they can integrate and pull from the data I publish. 

## Pain Points
It hard to work with SysML data outside of the SysML authoring tool and licensing tool and licenses are expensive

## Scenario Link
Insert Link to Scenario

## Acceptance Criteria
Given that the model is exposed, whenever i hit the API endpoint then I am able to extract the information and relationships contained in the model.

## Task List
- [ ] Export SysML Model into MATLAB System compoers
- [ ] Write function in MATLAB that takes the system composer model and exposes the attributes of the model, specifically to start with structural hierarchy and value attributes
- [ ] Need to generate a MATLAB microservice using MATLAB Compiler SDK
