### ISSUE TITLE
User Story 002: Expose UAF Models as an API

### ISSUE THREAD

**Issue by KBR-Autocorrect** [KBR-DREAMM-Team/Process-Documentation-Demo#2]
## Top Level
As a Systems Engineer, I want to expose the data I have authored in my UAF model so that others can consume it as well. 

## Pain Points
Same challenges as SysML

## Scenario Link
Insert Link to Scenario

## Acceptance Criteria
Given that i have authored a UAF model when I hit the API endpoint then I am able to extract the necessary information from UAF

## Task List
- [ ] Figure out a way to expose XML as an API endpoint
- [ ] Write a service that is geared toward that 
- [ ] Containerize Service
- [ ] Allow it import the exported XML from Cameo
- [ ] Run Web service
